import PersonClasses as pc
"""Модуль для создания экземпляров классов студентов, учетелей и сотрудников"""

# Создание студентов
student_1 = pc.Student("Алексеев", 18)
student_2 = pc.Student("Андреев", 19)
student_3 = pc.Student("Борисова", 20)
student_4 = pc.Student("Воронцова", 20)
student_5 = pc.Student("Галушкина", 21)
student_6 = pc.Student("Гурченкова", 19)
student_7 = pc.Student("Гуторов", 22)
student_8 = pc.Student("Деменкова", 20)
student_9 = pc.Student("Демочкин", 18)
student_10 = pc.Student("Калугин", 18)
student_11 = pc.Student("Киселева", 18)
student_12 = pc.Student("Коротков", 19)
student_13 = pc.Student("Кравчук", 18)
student_14 = pc.Student("Леонтьева", 19)
student_15 = pc.Student("Михальченков", 18)
student_16 = pc.Student("Мухин", 22)
student_17 = pc.Student("Остапенко", 20)
student_18 = pc.Student("Полохова", 19)
student_19 = pc.Student("Путятина", 18)
student_20 = pc.Student("Саврухина", 18)
student_21 = pc.Student("Симонова", 18)
student_22 = pc.Student("Степанов", 19)
student_23 = pc.Student("Усов", 18)
student_24 = pc.Student("Черненкова", 18)
student_25 = pc.Student("Черногузов", 21)
student_26 = pc.Student("Черткова", 12)
student_27 = pc.Student("Чайко", 18)
student_28 = pc.Student("Навальнев", 19)
student_29 = pc.Student("Шептухин", 18)
student_30 = pc.Student("Чипига", 22)
student_31 = pc.Student("Пищухин", 18)
student_32 = pc.Student("Подопригора", 19)
student_33 = pc.Student("Швецов", 18)
